name: Auto Deploy Go with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Build binary Go
        run: |
          go mod tidy
          go build -o myapp .

      - name: Jalankan dengan PM2
        run: |
          pm2 delete Golang-WebProfileAPI || true
          pm2 start ./myapp --name Golang-WebProfileAPI
          pm2 save
